[clusters]

[clusters.smdata]
addresses = [
  "http://124.236.111.103:9200",
  "http://124.236.111.104:9200",
  "http://124.236.111.105:9200"
]
index_default_open_days = 7
index_open_days = { fusion_cdn = 31 }
index_default_remain_days = 366

[clusters.mmdata]
addresses = [
  "http://124.236.111.112:9200",
  "http://124.236.111.113:9200",
  "http://124.236.111.114:9200"
]
index_default_open_days = 7
index_open_days = { billing = 3, ss = 3, squidlog-parent = 2, lemon = 31, areadata = 31, falcon = 31, heap = 31, node = 31}
index_default_remain_days = 155

[clusters.cloudy]
addresses = ["http://log-es-cloudy.bs58i.baishancdnx.com:9200"]
index_default_open_days = 14
index_open_days = {}
index_default_remain_days = 366