[clusters]

[clusters.c1]
addresses = [
  "http://1.1.1.1:9200",
  "http://1.1.1.2:9200",
  "http://1.1.1.3:9200"
]
index_default_open_days = 7
index_open_days = { index_a = 31 }
index_default_remain_days = 366

[clusters.c2]
addresses = [
  "http://2.2.2.1:9200",
  "http://2.2.2.2:9200",
  "http://2.2.2.3:9200"
]
index_default_open_days = 7
index_open_days = { index_a = 3, index_b = 3, index_c = 2}
index_default_remain_days = 155
